version: "2.1"
services:
  # PHPMyAdmin
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    labels:
      - io.docksal.virtual-host=pma-${VIRTUAL_HOST}
  # Adminer
  adminer:
    hostname: adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db # db is the default database container
      - ADMINER_PLUGINS=tables-filter tinymce # To load Adminer plugins
      - ADMINER_DESIGN=price # To use a bundled Adminer design
    labels:
      - io.docksal.virtual-host=adminer-${VIRTUAL_HOST}
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
